version: 2
jobs:
  test:
    docker:
      - image: node:10.24.1
    working_directory: /app
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn
      - run: ./node_modules/.bin/jest

workflows:
  version: 2
  run tests:
    jobs:
      - test
